spring.application.name=joblistingMongoDBReact

spring.data.mongodb.uri=mongodb+srv://JavaTechie:KirthySamayam%40225@javatechiespringdatanos.8lt3z4h.mongodb.net/?appName=JavaTechieSpringDataNoSQL
spring.data.mongodb.database=teluskoJobPortal

server.port=8080
